### ISSUE TITLE
在QtCreater中编辑功能失效

### ISSUE THREAD

**Issue by YH2021-cc** [spite-triangle/qt_servitor#1]
### 插件设置

![image](https://github.com/spite-triangle/qt_servitor/assets/84270940/c65007cc-7d83-4f12-883b-727f064eff5a)

### Qtcreater路径

![image](https://github.com/spite-triangle/qt_servitor/assets/84270940/e0d29d58-ba45-4862-8e5b-e107d4050b34)

**Comment by YH2021-cc** [comment]
@spite-triangle 有时间的话可以帮忙看下,谢谢!

**Comment by YH2021-cc** [comment]
解决了,原来还需要在插件QtTools里添加QtCreater的路径

**Comment by spite-triangle** [comment]
抱歉，现在才看见😂

星穹 ***@***.***> 于 2023年12月11日周一 17:03写道：
