### ISSUE TITLE
qmllsp无法使用

### ISSUE THREAD

**Issue by MaxWan007** [spite-triangle/qt_servitor#2]
作者您好，我使用的qt版本为6.6.3，在vscode中进行了该插件的配置，但无法成功启动qml的相关提示定义跳转功能，我觉得我应该是在c_cpp_properties.json这里卡住了，可否列出一个样本供参考

**Comment by spite-triangle** [comment]
> 作者您好，我使用的qt版本为6.6.3，在vscode中进行了该插件的配置，但无法成功启动qml的相关提示定义跳转功能，我觉得我应该是在c_cpp_properties.json这里卡住了，可否列出一个样本供参考

这个是由于lsp服务还未实现ts到c++的稳定关联启动，如果lsp服务启动失败，可以重启一下vscode。Qt官方开始入场提供插件，就摆烂拖着没修😅😅😅

**Comment by spite-triangle** [comment]
插件启动 LSP 服务异常问题已修复
